services:
  # Web service for the Flask app
  - type: web
    name: crypto-strategy-web
    env: python
    plan: free # Use the free instance type
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12 # Specify Python version
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-db
          property: connectionString

  # PostgreSQL database
  - type: psql
    name: crypto-db
    plan: free # Use the free database plan
    databaseName: crypto_strategy_db
    user: crypto_user

