services:
  - type: web
    name: web-crypto-strategy # Make sure this is your actual service name on Render
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --workers 1 --worker-class gevent app:app --timeout 120"
    plan: free # Or your current plan if different
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 # Or your current Python version if different
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-strategy-db # IMPORTANT: Replace this with the actual name of your Render PostgreSQL database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # This will generate a new secret key. If you have one set, you can keep your existing one.
      - key: FLASK_ENV
        value: production
